---
title: "Diary Entry Week 10"
author: "Chua Jieh Yih Audra"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 9

## Finalised topic (Changed)
I originally wanted to analyse the ratings for Animal Crossing by critics and users, and its sales in relation to that. However, upon receiving feedback on my dataset I have decided to change my topic.

My new topic is: what factors affect the number of streams a song gets on Spotify?

<br>

## Data sources I have curated so far
Here is my new data source: [https://www.kaggle.com/datasets/salvatorerastelli/spotify-and-youtube](https://www.kaggle.com/datasets/salvatorerastelli/spotify-and-youtube)

# Week 10

## What is the question that I am going to answer?
What factors affect the number of streams a song gets on Spotify?

## Why is this an important question? 
According to the Bulgarian Comparative Education Society (BCES), 2021, music is present everywhere around us, and acts as a medium which shapes our environment, self-perception, and interpersonal interactions, thus leaving a large impact on society. Source: [https://files.eric.ed.gov/fulltext/ED614071.pdf](https://files.eric.ed.gov/fulltext/ED614071.pdf)

According to Business of Apps statistics for 2023, Spotify is the most popular music streaming platform in the world, and it has over 350 million users and 150 million subscribers. Source: [https://www.businessofapps.com/data/music-streaming-market/](https://www.businessofapps.com/data/music-streaming-market/)

Finally, according to Statista, in 2022, total revenue generated by the recorded music industry was 26.2 billion U.S. dollars, of which the majority of revenue came from streaming services, showing the economic significance they have. Source: [https://www.statista.com/chart/4713/global-recorded-music-industry-revenues/](https://www.statista.com/chart/4713/global-recorded-music-industry-revenues/)

## Which rows and columns of the dataset will be used to answer this question? 
Rows: all
Columns: Stream, Danceability, Energy, Speechiness, Instrumentalness, Liveness, Valence, Tempo, Duration_ms, Views, Likes, Title, Description, Licensed, official_video

Upon opening my dataset in Excel, it gave me a message letting me know that some numbers had gotten stored as text. Excel helped me to automate the process of fixing these and converting them back to numbers.
